language: node_js
sudo: required
node_js:
  - '4.1.x'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm run typings
script: npm run build